name: Daily Chat Summary

on:
  schedule:
    - cron: '0 5 * * *' # Jam 12:00 WIB (UTC+7)
  workflow_dispatch: # Biar bisa manual juga

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install node-fetch
        run: npm install node-fetch@2

      - name: Run Supabase summary script
        run: node your-script.js
        env:
          API_KEY: ${{ secrets.SUPABASE_API_KEY }}
